project_id = "shydpfwuvnlzdzbubmgb"

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-group-invitation]
verify_jwt = true

[functions.accept-group-invitation]
verify_jwt = true

[functions.decline-group-invitation]
verify_jwt = true

