project_id = "shydpfwuvnlzdzbubmgb"

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-google-client-id]
verify_jwt = false

[functions.send-group-invitation]
verify_jwt = true

[functions.accept-group-invitation]
verify_jwt = true

[functions.decline-group-invitation]
verify_jwt = true

[functions.google-fit-sync]
verify_jwt = true

[functions.analyze-air-quality]
verify_jwt = true